### ISSUE TITLE
[勘误] 15.2 “使用ServiceWorker进行缓存”，`IndexDB`应当为`IndexedDB`

### ISSUE THREAD

**Issue by gogoend** [xcodebuild/perfbook#3]
15.2 “使用ServiceWorker进行缓存”，`IndexDB`应当为`IndexedDB`

（第201页）

相关资料：

1. [IndexedDB 规范](https://www.w3.org/TR/IndexedDB/)

2. Chrome 截图

    <img width="266" alt="image" src="https://user-images.githubusercontent.com/26410985/205504225-7d773796-0577-4d76-be7b-700ff7c36482.png">

**Comment by xcodebuild** [comment]
确实，感谢，已经加入勘误和 contributors
