### ISSUE TITLE
[疑问] 12.2 第166页倒数第10行“……这意味着解析、执行 JavaScript、重新布局等依赖主线程完成的动画……”

### ISSUE THREAD

**Issue by gogoend** [xcodebuild/perfbook#4]
12.2 第166页倒数第10行“……这意味着解析、执行 JavaScript、重新布局等依赖主线程完成的动画……”

这句话里的“解析”后面好像少了宾语，让我有点点不清楚这里原本要表达的是什么，即“解析的是什么东西”。

- 如果结合下文无序列表第一、二项的内容，解析的“东西”是指“HTML / CSS”

- 如果单看这句话，解析的“东西”又可以是“JavaScript” （“执行”的宾语）

所以这里原本要表达的是什么呢？

**Comment by xcodebuild** [comment]
应该是指解析和执行 JavaScript，确实表达会引起费解，我补充到勘误中

**Comment by gogoend** [comment]
不过，感觉有时候类似这样
```
(谓语)、(谓语)(宾语)、(宾语)
```
的句子确实有些难表达；比如我在写博客或者 Git Commit 信息的时候，写到这样的句子，就会很纠结 🥴
