### ISSUE TITLE
[疑问] 13.1 第176页第3行“通过这种方式，JavaScript代码在单进程下运行” 这句话中的“进程”是不是应当为“线程”？

### ISSUE THREAD

**Issue by gogoend** [xcodebuild/perfbook#5]
13.1 第176页第3行“通过这种方式，JavaScript代码在单进程下运行” 这句话中的“进程”是不是应当为“线程”？

1. 联系了一下上下文，以及插图，似乎一直都没提到“进程”这个概念，这里提到了，有点突兀
2. 13.1 开头部分强调了“在浏览器中，JavaScript代码是运行在单线程上的”，此处“单进程”的描述应当是否与“单线程”保持一致？

**Comment by xcodebuild** [comment]
是的， 应该修正为“线程”，感谢
