### ISSUE TITLE
[勘误] 11.1 151页 图11-2 上方文字倒数第4行 “content-encoding：作为 Request Header 让服务器端表明传输内容的解压缩……”，`Request Header`应当为`Response Header`

### ISSUE THREAD

**Issue by gogoend** [xcodebuild/perfbook#7]
11.1 151页 图11-2 上方文字倒数第4行 “content-encoding：作为 Request Header 让服务器端表明传输内容的解压缩……”，`Request Header`应当为`Response Header`

1. 根据图11-2，`content-encoding`是由服务端响应给客户端的，因此`content-encoding`应该是`Response Header`的字段
2. 实际看了下请求，看起来`content-encoding`确实位于`Response Header`中

    <img width="871" alt="image" src="https://user-images.githubusercontent.com/26410985/209192397-6afc9b01-fe23-49d0-a1f9-906b53283c64.png">

**Comment by xcodebuild** [comment]
已修正
