### ISSUE TITLE
[勘误] 11.2 157页 第2行 “If-Modified-Since/Last-Modified” 格式应当是小标题，不是代码

### ISSUE THREAD

**Issue by gogoend** [xcodebuild/perfbook#8]
11.2 157页 第2行 “If-Modified-Since/Last-Modified” 文本格式应该是小标题，不是代码

1. 此处应与上一个小标题 “If-None-Match/ETag” （156页 倒数第8行）文本格式保持一致。

**Comment by xcodebuild** [comment]
细致，感谢
